import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-100">
      <body className={inter.className}>
        <main className="">
          <header className="flex items-center justify-between p-4 bg-white shadow">
            <div className="max-w-screen-xl  ">
              <Link href={"/"}>
                <h1 className="text-2xl font-bold">
                  <span className="text-blue-600">IA</span>{" "}
                  <span className="text-gray-700">for Docs</span>
                </h1>
              </Link>
            </div>
          </header>
          {children}
        </main>
      </body>
    </html>
  );
}
